language: php

sudo: false

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - hhvm
  - nightly

script:
  - ant travis

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
