language: php

sudo: false

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.4'
  - '8.0'
  - nightly

before_script:
  - travis_retry composer install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader

script:
  - ant travis

